Add support for basic hash/object conversions
infinyon/node-bindgen pull request #201
Opened 2022-08-13 00:41 UTC by superstator

Addresses #169

2022-08-14 02:46 UTC, simlay requested changes
Hi there! Thanks for the contribution!

At first glance, I think this is pretty good. I've got a few nits.

- [ ] Add to the [`CHANGELOG.md`](https://github.com/infinyon/node-bindgen/blob/master/CHANGELOG.md).
- [ ] Remove or make add more of a description to the `README.md` in the hash example.

I don't wanna expand the scope of this task too much but I wonder if we care about `impl<'a, T> JSValue<'a> for  HashMap<U, T> where U: Eq + Hash + JSValue, T: JSValue` (and `TryIntoJS`). Thoughts?

2022-08-14 02:46 UTC, simlay commented on examples/hash/README.md
> +return json object
I'm confused by this README.

2022-08-14 03:36 UTC, superstator commented
Ha, I used the array example as a template and obviously missed some cruft. I will update the readme and changelog, and give the additional impl some thought.

2022-08-20 17:47 UTC, superstator commented
I played around a little with the idea of a generic hash key type, but I think it would effectively mean needing to support `Map()` on the JS side, which is not a slam dunk via NAPI. Doable, but maybe best left until somebody has a strong need for it.

2022-08-22 18:28 UTC, simlay reviewed
LGTM! Thanks!

2022-08-22 19:33 UTC, digikata approved these changes

2022-08-22 19:36 UTC, sehz commented
bors r+

2022-10-20 16:32 UTC, closed without merging

2023-05-20 06:43 UTC, yannleretaille commented
Was there a reason this wasn't merged? It'd be very useful to have native support for HashMap.